# Generated by Django 6.0 on 2025-12-08 16:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal campaign name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sponsor_type', models.CharField(choices=[('PLATFORM', 'Platform'), ('VENDOR', 'Vendor')], default='PLATFORM', max_length=20)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('CART', 'Cart'), ('DELIVERY', 'Delivery')], default='CART', max_length=20)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_transactions_per_user_day', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Order identifier used to ensure idempotency', max_length=255)),
                ('applied_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='app.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date', 'is_active'], name='app_campaig_start_d_8ae6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['user', 'campaign', 'redeemed_at'], name='app_redempt_user_id_0becb2_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['campaign', 'redeemed_at'], name='app_redempt_campaig_f3f8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['order_id'], name='app_redempt_order_i_ddf756_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='redemption',
            unique_together={('campaign', 'order_id')},
        ),
    ]
